version: '3'

networks:
  web: ~

services:
  php:
    container_name: ${COMPOSE_PROJECT_NAME}_php
    build:
      context: docker/php
      args:
        - BITBUCKET_USER=${BITBUCKET_USER}
        - BITBUCKET_PASSWORD=${BITBUCKET_PASSWORD}
        - BITBUCKET_REPOSITORY_URL=${BITBUCKET_REPOSITORY_URL}
        - APP_VERSION=${APP_VERSION}
    networks:
      web:
        aliases:
          - php_${COMPOSE_PROJECT_NAME}

  apache:
    container_name: ${COMPOSE_PROJECT_NAME}_apache
    build:
      context: docker/apache
    depends_on:
      - php
    environment:
      - NAMESERVER=${NAMESERVER}
      - SSL_MODE=${SSL_MODE}
      - AUTOSIGNED_CERT=${AUTOSIGNED_CERT}
      - HTTPD_LOG_DIR=/usr/local/apache2/logs
      - HTTPD_PORT=${HTTPD_PORT}
      - PHP_FPM_HANDLER=php_${COMPOSE_PROJECT_NAME}
    networks:
      - web

  database:
    container_name: ${COMPOSE_PROJECT_NAME}_database
    image: mongo:4.1-xenial
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${ROOT_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${ROOT_DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${ROOT_DB_NAME}
    networks:
      - web

  webpack:
    container_name: ${COMPOSE_PROJECT_NAME}_webpack
    build:
      context: ./docker/webpack
    depends_on:
      - php
    env_file:
      - .env
    volumes:
      - ./:/app
    networks:
      - web
